export class FlightAudio{
  constructor(){this.ctx=null;this.master=null;this.engine=null;this.engineGain=null;this.volume=.35;this.previousVolume=.35;}
  init(){if(this.ctx)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);const o=this.ctx.createOscillator();o.type='sawtooth';o.frequency.value=57;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=180;this.engineGain=this.ctx.createGain();this.engineGain.gain.value=.055;o.connect(filter);filter.connect(this.engineGain);this.engineGain.connect(this.master);o.start();this.engine={osc:o,filter};const len=this.ctx.sampleRate*2;this.noiseBuffer=this.ctx.createBuffer(1,len,this.ctx.sampleRate);const data=this.noiseBuffer.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.random()*2-1;}
  setVolume(value){this.volume=Math.max(0,Math.min(1,value));if(this.volume>0)this.previousVolume=this.volume;if(this.ctx)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.03);}
  toggleMute(){this.setVolume(this.volume?0:this.previousVolume);return this.volume;}
  update(throttle,speed){if(!this.ctx||!this.engine)return;this.engine.osc.frequency.setTargetAtTime(43+throttle*67+speed*.04,this.ctx.currentTime,.08);this.engine.filter.frequency.setTargetAtTime(125+throttle*470,this.ctx.currentTime,.1);this.engineGain.gain.setTargetAtTime(.025+throttle*.08,this.ctx.currentTime,.1);}
  tone(freq,duration=.12,type='sine',gain=.15,endFreq=freq){if(!this.ctx)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(1,endFreq),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);}
  noise(duration=.3,gain=.16,filterFreq=900,endFreq=90){if(!this.ctx)return;const t=this.ctx.currentTime,src=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),g=this.ctx.createGain();src.buffer=this.noiseBuffer;filter.type='lowpass';filter.frequency.setValueAtTime(filterFreq,t);filter.frequency.exponentialRampToValueAtTime(Math.max(30,endFreq),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(filter);filter.connect(g);g.connect(this.master);src.start(t,Math.random()*Math.max(0,2-duration-.01),duration);}
  click(){this.tone(720,.07,'triangle',.08,510);}
  lock(){this.tone(920,.15,'sine',.12,1250);}
  missile(){this.tone(95,.5,'sawtooth',.16,480);this.noise(.75,.13,2500,320);}
  gun(){this.noise(.1,.2,2200,250);this.tone(120,.09,'triangle',.08,52);}
  explosion(){this.noise(1.3,.32,920,70);this.tone(68,.85,'sawtooth',.2,28);this.noise(.35,.12,3600,500);}
  warning(){this.tone(720,.13,'square',.12,720);}
}
